### ISSUE TITLE
Unexpected I2C device at 0x00 when this sensor is plugged in

### ISSUE THREAD

**Issue by ullix** [adafruit/Adafruit_SGP30#16]
I just got the Adafruit_SGP30 sensor, ran the provided test, and it gives the expected output. Good.

But when I scan the I2C bus I see the 0x58 (this sensor, ok), plus other sensors (ok), plus also a "Device" at 0x00. It is present ONLY when the SGP30 is also present, and absent with any of the other 3 sensors.

I think it should not be there?  What is this?

**Comment by ladyada** [comment]
that's an all-call address, its normal
