### ISSUE TITLE
softReset

### ISSUE THREAD

**Issue by bytesontherocks** [adafruit/Adafruit_SGP30#19]
Hello, 

I'm not using your library but having a look at your code I noticed that Adafruit_SGP30::softReset has the following issue:

The reset command shouldn't be{ i2c_addr, 0x00, 0x06} but {0x00, 0x06}

I can see 2 quick ways to fix it:

1.  Modify readWordFromCommand to take the device address as a parameter with SGP30_I2CADDR_DEFAULT as default and pass 0 when softReset is called

or

2.   Do 
{
 _i2c->beginTransmission(0x00);
 _i2c->write(0x06);
_i2c->endTransmission();
}
with the magical numbers in macros/ constexpr?

What do you think?

**Comment by bytesontherocks** [comment]
@PepperBurst, I see that you created a pull request for the Soft Reset. What do think about my comment?

**Comment by PepperBurst** [comment]
@bytesontherocks Hi I'm sorry for overlooking this. Looking back at my previous code which is
```cpp
#ifdef ENABLE_DEBUG
	Serial.println(F("Soft Reset"));
#endif
	Wire.beginTransmission(SOFT_RESET_ADDR);
	Wire.write(SOFT_RESET_CMD);
	Wire.endTransmission();
#ifdef ENABLE_DEBUG
	Serial.println(F("Resetting..."));
#endif
```
you are very much right in that regard. Apologies, this is my bad.
