### ISSUE TITLE
Commenting error

### ISSUE THREAD

**Issue by Eths33** [adafruit/Adafruit_SGP30#23]
In the file Adafruit_SGP30.h on lines 58 - 68 the same comment was used 3 times referencing CO2. As a result H2 and Ethanol do not have a comment.

**Comment by caternuson** [comment]
Yep, looks like a copy paste error, and the resulting dox are also as expected:
![image](https://user-images.githubusercontent.com/8755041/142448567-b90b07e8-5b5b-4e36-9e81-7985071c2800.png)

Thanks for spotting that. Want to submit a PR to fix?

**Comment by Eths33** [comment]
I noticed this again when I returned to working on my project. 
I submitted a pull request.

**Comment by caternuson** [comment]
Looks like the pull request (#24) was closed? Is there a plan to reopen or resubmit it?

**Comment by caternuson** [comment]
Closing. Fixed with #30.
