### ISSUE TITLE
Humidity compensation

### ISSUE THREAD

**Issue by Fred10932** [adafruit/Adafruit_SGP30#3]
From the [SGP30 doc](https://www.sensirion.com/fileadmin/user_upload/customers/sensirion/Dokumente/9_Gas_Sensors/Sensirion_Gas_Sensors_SGP30_Datasheet_EN.pdf):

> Humidity Compensation
> The SGP30 features an on-chip humidity compensation for the air quality signals (CO2eq and TVOC) and sensor raw signals (H2-signal and Ethanol_signal). To use the on-chip humidity compensation an absolute humidity value from an external humidity sensor like the SHTxx is required. Using the “Set_humidity” command, a new humidity value can be written to the SGP30 by sending 2 data bytes (MSB first) and 1 CRC byte. The 2 data bytes represent humidity values as a fixed-point 8.8bit number with a minimum value of 0x0001 (=1/256 g/m3) and a maximum value of 0xFFFF (255 g/m3 + 255/256 g/m3). For instance, sending a value of 0x0F80 corresponds to a humidity value of 15.50 g/m3 (15 g/m3 + 128/256 g/m3).
> After setting a new humidity value, this value will be used by the on-chip humidity compensation algorithm until a new humidity value is set using the “Set_humidity” command. Restarting the sensor (power-on or soft reset) or sending a value of 0x0000 (= 0 g/m3) sets the humidity value used for compensation to its default value (0x0B92 = 11.57 g/m3) until a new humidity value is sent. Sending a humidity value of 0x0000 can therefore be used to turn off the humidity compensation.

Facilitating this would be greatly appreciated :)

**Comment by mguntli** [comment]
see my pull request https://github.com/adafruit/Adafruit_SGP30/pull/4

**Comment by ladyada** [comment]
added!
